const colors = {
  light: {
    text: "#0A1E0F",
    tint: "#0D5C3A",
    background: "#F5F9F6",
    foreground: "#0A1E0F",
    card: "#FFFFFF",
    cardForeground: "#0A1E0F",
    primary: "#0D5C3A",
    primaryForeground: "#FFFFFF",
    primaryLight: "#1A8A5A",
    secondary: "#E8F5EE",
    secondaryForeground: "#0D5C3A",
    muted: "#EEF4F0",
    mutedForeground: "#6B8C7A",
    accent: "#C8972A",
    accentForeground: "#FFFFFF",
    accentLight: "#F0BB54",
    destructive: "#D94F4F",
    destructiveForeground: "#FFFFFF",
    border: "#D4E8DC",
    input: "#D4E8DC",
    surface: "#FFFFFF",
    overlay: "rgba(0,0,0,0.4)",
  },
  dark: {
    text: "#E8F5EE",
    tint: "#25D98A",
    background: "#0B1A2E",
    foreground: "#E8F5EE",
    card: "#122040",
    cardForeground: "#E8F5EE",
    primary: "#1DB874",
    primaryForeground: "#FFFFFF",
    primaryLight: "#25D98A",
    secondary: "#1A2B46",
    secondaryForeground: "#E8F5EE",
    muted: "#1A2B46",
    mutedForeground: "#8FA8C0",
    accent: "#F0BB54",
    accentForeground: "#0B1A2E",
    accentLight: "#F7D57A",
    destructive: "#D94F4F",
    destructiveForeground: "#FFFFFF",
    border: "#1E3050",
    input: "#1E3050",
    surface: "#1A2B46",
    overlay: "rgba(0,0,0,0.6)",
  },
  radius: 16,
};

export default colors;
